# Fix MySQL 8.0 authentication for MLMD
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-fix-auth
  namespace: kubeflow
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.0.26
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for MySQL to be ready..."
          until mysql -h mysql -u root -e "SELECT 1" > /dev/null 2>&1; do
            echo "MySQL not ready, waiting..."
            sleep 5
          done
          echo "MySQL is ready, applying fixes..."
          mysql -h mysql -u root << 'EOF'
          ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';
          CREATE DATABASE IF NOT EXISTS mlpipeline;
          CREATE DATABASE IF NOT EXISTS metadb;
          GRANT ALL PRIVILEGES ON mlpipeline.* TO 'root'@'%';
          GRANT ALL PRIVILEGES ON metadb.* TO 'root'@'%';
          FLUSH PRIVILEGES;
          EOF
          echo "MySQL fixes applied successfully!"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      restartPolicy: OnFailure