apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: viewers.kubeflow.org
spec:
  group: kubeflow.org
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              podTemplateSpec:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              type:
                type: string
                enum: ["tensorboard", "notebook"]
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
  scope: Namespaced
  names:
    plural: viewers
    singular: viewer
    kind: Viewer