apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Stage 1: CRDs and Basic Infrastructure
# This stage must complete before proceeding to stage 2
resources:
  # Create required namespaces first
  - ../../../../manifests/common/kubeflow-namespace/base
  - ../../../../manifests/common/istio-1-24/istio-namespace/base
  
  # Apply CRDs before any resources that depend on them
  - ../../../../manifests/common/istio-1-24/istio-crds/base
  - ../../../../manifests/apps/admission-webhook/upstream/base/crd.yaml
  - ../../../../manifests/common/cert-manager/base
  
  # Basic infrastructure components
  - ../../../../manifests/common/istio-1-24/istio-install/base